# Generated by Django 5.1.1 on 2024-10-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0100_alter_pchartdata_date_control_limits_calculated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlchartstatistics',
            name='lsl',
            field=models.FloatField(default=355),
        ),
        migrations.AddField(
            model_name='controlchartstatistics',
            name='usl',
            field=models.FloatField(default=375),
        ),
    ]
