# Generated by Django 5.1.1 on 2024-10-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0101_controlchartstatistics_lsl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlchartreading',
            name='lsl',
            field=models.FloatField(blank=True, default=355, null=True),
        ),
        migrations.AddField(
            model_name='controlchartreading',
            name='usl',
            field=models.FloatField(blank=True, default=375, null=True),
        ),
    ]
